namespace:
  name: staging

service:
  port: 5000

image:
  tag: "3.0"
  pullPolicy: Always

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-argocd"
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: demoapp.ndthang.live
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: hello-k8s
          servicePort: 5000
  tls:
    - hosts:
        - demoapp.ndthang.live
      secretName: hello-k8s-ingress
