namespace:
  name: default

service:
  type: ClusterIP
  svc:
    http: 5000
    # grpc: ToBeDefined
    https: 443

image:
  repository: nthang621/learn-argocd-k8s
  tag: "v1"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

containerPort: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []
